### ISSUE TITLE
Texture bug Archery Artisan Table

### ISSUE THREAD

**Issue by Mozork01** [ZsoltMolnarrr/Archers#3]
![2023-11-08_14 18 50](https://github.com/ZsoltMolnarrr/Archers/assets/148884018/3cebdda4-f9c7-4630-97d5-a7d1b2f52704)
![2023-11-08_14 18 55](https://github.com/ZsoltMolnarrr/Archers/assets/148884018/49e6dfde-57be-4347-8873-f19d8f34b28c)

**Comment by xR4YM0ND** [comment]
Same here, its flickering for like 2 sec (if standing still) than it catchs itself

**Comment by ZsoltMolnarrr** [comment]
Ohh wow, totally my mistake, forgot to check this block without shaders.
Will be patched soon.

**Comment by ZsoltMolnarrr** [comment]
Fixed in 1.0.3

**Comment by Moozipan** [comment]
Just fyi it's not entirely fixed on my end, since there's still some z-fighting where the textures overlap on the table legs. Much less noticeable, but it occurs regardless of shaders. It should be fully fixed though with the texture from the previous version (the one with the gaps).

**Comment by ZsoltMolnarrr** [comment]
Ohh god this block... :D

**Comment by ZsoltMolnarrr** [comment]
A fix will be available in 1.0.4.
